-- ============================================================
-- POPOK Current Database Baseline
--
-- Reference snapshot of the current schema.
-- Not part of Supabase migration history.
-- Do NOT execute against an existing production database.
-- Use only as documentation or when initializing a brand-new database.
-- ============================================================

-- Extensions
create extension if not exists "uuid-ossp" with schema extensions;
create extension if not exists "pgcrypto" with schema extensions;

-- ============================================================================
-- Shared Helper Functions & Triggers
-- ============================================================================

create or replace function public.set_updated_at()
returns trigger as $$
begin
  new.updated_at = now();
  return new;
end;
$$ language plpgsql;


-- ============================================================================
-- 1. public.profiles
-- ============================================================================

create table if not exists public.profiles (
  id uuid primary key references auth.users (id) on delete cascade,

  email text,
  display_name text not null,
  username text unique,
  avatar_url text,

  profile_type text default 'artist'
    check (profile_type in ('artist', 'organization', 'admin')),

  onboarding_completed boolean default false,

  status text not null default 'active'
    check (status in ('active', 'suspended')),

  created_at timestamptz not null default timezone('utc'::text, now()),
  updated_at timestamptz not null default timezone('utc'::text, now())
);

drop trigger if exists trg_profiles_updated_at on public.profiles;
create trigger trg_profiles_updated_at
  before update on public.profiles
  for each row
  execute function public.set_updated_at();

alter table public.profiles enable row level security;

drop policy if exists "Users can view their own profile" on public.profiles;
create policy "Users can view their own profile"
  on public.profiles
  for select
  to authenticated
  using (id = auth.uid());

drop policy if exists "Users can insert their own profile" on public.profiles;
create policy "Users can insert their own profile"
  on public.profiles
  for insert
  to authenticated
  with check (id = auth.uid());

drop policy if exists "Users can update their own profile" on public.profiles;
create policy "Users can update their own profile"
  on public.profiles
  for update
  to authenticated
  using (id = auth.uid())
  with check (id = auth.uid());

-- Trigger function for creating profile on auth.users signup
create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer
as $$
begin
  insert into public.profiles (id, email, display_name, avatar_url, onboarding_completed, profile_type, status)
  values (
    new.id,
    new.email,
    coalesce(new.raw_user_meta_data->>'full_name', new.raw_user_meta_data->>'name', '새 사용자'),
    coalesce(new.raw_user_meta_data->>'avatar_url', new.raw_user_meta_data->>'picture', ''),
    false,
    'artist',
    'active'
  )
  on conflict (id) do nothing;
  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
  after insert on auth.users
  for each row
  execute function public.handle_new_user();


-- ============================================================================
-- 2. public.submissions
-- ============================================================================

create table if not exists public.submissions (
  id bigint generated by default as identity primary key,

  name text not null,
  email text not null,
  instagram text,
  genre text not null,

  bio_short text,
  profile_image_url text,
  profile_image_urls jsonb not null default '[]'::jsonb
    check (jsonb_typeof(profile_image_urls) = 'array'),
  motion_video_url text,

  works jsonb not null default '[]'::jsonb
    check (jsonb_typeof(works) = 'array'),

  additional_requests text,

  status text not null default 'pending'
    check (status in ('pending', 'reviewing', 'approved', 'rejected')),

  claim_code text unique,
  public_slug text unique,

  parsed_profile jsonb,
  parsed_at timestamptz,
  parser_status text default 'not_parsed'
    check (parser_status in ('not_parsed', 'parsing', 'parsed', 'reviewed', 'error')),
  parser_error text,

  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

create index if not exists idx_submissions_email on public.submissions (email);
create index if not exists idx_submissions_name on public.submissions (name);
create index if not exists submissions_works_gin_idx on public.submissions using gin (works);

drop trigger if exists trg_submissions_updated_at on public.submissions;
create trigger trg_submissions_updated_at
  before update on public.submissions
  for each row
  execute function public.set_updated_at();

alter table public.submissions enable row level security;


-- ============================================================================
-- 3. public.artists
-- ============================================================================

create table if not exists public.artists (
  id uuid primary key default gen_random_uuid(),
  owner_id uuid references auth.users (id) on delete set null,

  name text not null,
  name_en text,
  slug text unique,

  company text,
  genre text,
  role text,
  city_or_region text,
  category text,

  status text default 'published',
  verified boolean default false,

  bio text,
  bio_short text,

  review_links jsonb default '[]'::jsonb,
  portfolio_url text,

  profile_image_url text,
  profile_image_urls jsonb default '[]'::jsonb,
  motion_video_url text,
  youtube_url text,
  youtube_preview_start integer default 0,
  youtube_preview_end integer default 15,

  works jsonb not null default '[]'::jsonb
    check (jsonb_typeof(works) = 'array'),
  affiliations jsonb default '[]'::jsonb,
  current_activity jsonb default '[]'::jsonb,
  awards jsonb default '[]'::jsonb,
  competitions jsonb default '[]'::jsonb,
  education jsonb default '[]'::jsonb,
  links jsonb default '[]'::jsonb,

  email text,
  instagram text,
  website text,

  artist_type text,
  submission_id bigint references public.submissions (id) on delete set null,

  claim_code text unique,
  is_demo boolean default false,
  motion_intro text,
  view_count bigint not null default 0,

  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

create index if not exists artists_owner_id_idx on public.artists (owner_id);
create unique index if not exists artists_owner_id_unique_idx on public.artists (owner_id) where owner_id is not null;
create index if not exists artists_works_gin_idx on public.artists using gin (works);
create index if not exists artists_view_count_idx on public.artists (view_count desc);
create index if not exists artists_submission_id_idx on public.artists (submission_id);

drop trigger if exists trg_artists_updated_at on public.artists;
create trigger trg_artists_updated_at
  before update on public.artists
  for each row
  execute function public.set_updated_at();

alter table public.artists enable row level security;

drop policy if exists "Public can view published artists" on public.artists;
create policy "Public can view published artists"
  on public.artists
  for select
  to anon, authenticated
  using (status = 'published');

drop policy if exists "Users can view own artist" on public.artists;
create policy "Users can view own artist"
  on public.artists
  for select
  to authenticated
  using (auth.uid() = owner_id);

drop policy if exists "Users can create own artist" on public.artists;
create policy "Users can create own artist"
  on public.artists
  for insert
  to authenticated
  with check (auth.uid() = owner_id);

drop policy if exists "Users can update own artist" on public.artists;
create policy "Users can update own artist"
  on public.artists
  for update
  to authenticated
  using (auth.uid() = owner_id)
  with check (auth.uid() = owner_id);

drop policy if exists "Users can delete own artist" on public.artists;
create policy "Users can delete own artist"
  on public.artists
  for delete
  to authenticated
  using (auth.uid() = owner_id);

create or replace function public.increment_artist_view_count(identifier text)
returns bigint
language plpgsql
as $$
declare
  new_count bigint;
begin
  update public.artists
  set view_count = view_count + 1
  where status = 'published'
    and (id::text = identifier or slug = identifier)
  returning view_count into new_count;

  return new_count;
end;
$$;


-- ============================================================================
-- 4. public.companies
-- ============================================================================

create table if not exists public.companies (
  id uuid primary key default gen_random_uuid(),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),

  status text not null default 'draft' check (status in ('draft', 'published', 'archived')),
  verified boolean not null default false,

  name text not null,
  name_en text,
  slug text,

  genre text,
  category text,
  city_or_region text,
  founded_year integer,

  slogan text,
  mission text,
  vision text,
  core_values jsonb not null default '[]'::jsonb,

  bio_short text,
  bio text,
  brand_color text default '#C8EE52',

  logo_url text,
  profile_image_url text,
  profile_image_urls jsonb not null default '[]'::jsonb,
  hero_image_url text,
  motion_video_url text,

  email text,
  instagram text,
  website text,
  portfolio_url text,

  current_activity jsonb not null default '[]'::jsonb,
  works jsonb not null default '[]'::jsonb,
  history jsonb not null default '[]'::jsonb,
  awards jsonb not null default '[]'::jsonb,
  review_links jsonb not null default '[]'::jsonb,
  links jsonb not null default '[]'::jsonb,

  owner_id uuid references auth.users (id) on delete set null,

  ai_draft jsonb,
  ai_draft_status text not null default 'not_started'
    check (ai_draft_status in ('not_started', 'processing', 'ready', 'failed', 'applied')),
  ai_draft_generated_at timestamptz,
  ai_draft_error text,

  source_file_path text,
  source_file_name text,
  source_file_size bigint,
  source_file_uploaded_at timestamptz,
  source_text text,
  source_material_updated_at timestamptz,
  ai_draft_source_summary jsonb
);

create unique index if not exists companies_slug_key on public.companies (slug) where slug is not null;
create index if not exists companies_status_idx on public.companies (status);
create index if not exists companies_name_idx on public.companies (name);

drop trigger if exists trg_companies_updated_at on public.companies;
create trigger trg_companies_updated_at
  before update on public.companies
  for each row
  execute function public.set_updated_at();

alter table public.companies enable row level security;

drop policy if exists "Public can view published companies" on public.companies;
create policy "Public can view published companies"
  on public.companies
  for select
  to anon, authenticated
  using (status = 'published');

drop policy if exists "Owners can view their companies" on public.companies;
create policy "Owners can view their companies"
  on public.companies
  for select
  to authenticated
  using (owner_id = auth.uid());

drop policy if exists "Owners can update their companies" on public.companies;
create policy "Owners can update their companies"
  on public.companies
  for update
  to authenticated
  using (owner_id = auth.uid())
  with check (owner_id = auth.uid());


-- ============================================================================
-- 5. public.artist_companies
-- ============================================================================

create table if not exists public.artist_companies (
  id uuid primary key default gen_random_uuid(),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),

  artist_id uuid not null references public.artists (id) on delete cascade,
  company_id uuid not null references public.companies (id) on delete cascade,

  role text,
  start_year integer,
  end_year integer,

  is_current boolean not null default true,
  is_primary boolean not null default false
);

create index if not exists artist_companies_artist_idx on public.artist_companies (artist_id);
create index if not exists artist_companies_company_idx on public.artist_companies (company_id);

create unique index if not exists artist_companies_unique_relation_idx
  on public.artist_companies (artist_id, company_id, coalesce(lower(trim(role)), ''));

create unique index if not exists artist_companies_primary_current_idx
  on public.artist_companies (artist_id)
  where is_primary = true and is_current = true;

drop trigger if exists trg_artist_companies_updated_at on public.artist_companies;
create trigger trg_artist_companies_updated_at
  before update on public.artist_companies
  for each row
  execute function public.set_updated_at();

alter table public.artist_companies enable row level security;

drop policy if exists "Public can read published artist-company links" on public.artist_companies;
create policy "Public can read published artist-company links"
  on public.artist_companies
  for select
  to anon, authenticated
  using (
    exists (select 1 from public.artists a where a.id = artist_id and a.status = 'published')
    and exists (select 1 from public.companies c where c.id = company_id and c.status = 'published')
  );


-- ============================================================================
-- 6. public.organization_applications
-- ============================================================================

create table if not exists public.organization_applications (
  id uuid primary key default gen_random_uuid(),

  org_name text not null,
  contact_name text not null,
  email text not null,
  phone text not null,
  instagram text not null,

  portfolio_text text,
  logo_url text,

  resume_file_path text,
  resume_file_name text,
  resume_file_size bigint,

  company_id uuid references public.companies (id) on delete set null,

  status text not null default 'pending'
    check (status in ('pending', 'approved', 'rejected')),

  deprecated_website_description_backup jsonb,

  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists organization_applications_status_created_at_idx
  on public.organization_applications (status, created_at desc);

create index if not exists organization_applications_company_id_idx
  on public.organization_applications (company_id);

drop trigger if exists trg_organization_applications_updated_at on public.organization_applications;
create trigger trg_organization_applications_updated_at
  before update on public.organization_applications
  for each row
  execute function public.set_updated_at();

alter table public.organization_applications enable row level security;


-- ============================================================================
-- 7. public.performances
-- ============================================================================

create table if not exists public.performances (
  id uuid primary key default gen_random_uuid(),

  title text not null,
  slug text,

  description text,

  poster_url text,
  source_url text,
  ticket_url text,
  external_url text,

  venue text,
  start_date date,
  end_date date,

  organizer text,
  genre text,
  category text,

  status text not null default 'draft' check (status in ('draft', 'published', 'archived')),
  featured boolean not null default false,
  display_order integer default 0,

  external_id text,
  company_id uuid references public.companies (id) on delete set null,

  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create unique index if not exists performances_slug_key on public.performances (slug) where slug is not null;
create unique index if not exists performances_external_id_key on public.performances (external_id) where external_id is not null;
create index if not exists performances_status_start_date_idx on public.performances (status, start_date);
create index if not exists performances_featured_idx on public.performances (featured) where featured = true;
create index if not exists performances_company_id_idx on public.performances (company_id);

drop trigger if exists trg_performances_updated_at on public.performances;
create trigger trg_performances_updated_at
  before update on public.performances
  for each row
  execute function public.set_updated_at();

alter table public.performances enable row level security;

drop policy if exists "Public can read published performances" on public.performances;
create policy "Public can read published performances"
  on public.performances
  for select
  to anon, authenticated
  using (status = 'published');


-- ============================================================================
-- 8. public.performance_artists
-- ============================================================================

create table if not exists public.performance_artists (
  id uuid primary key default gen_random_uuid(),

  performance_id uuid not null references public.performances (id) on delete cascade,
  artist_id uuid not null references public.artists (id) on delete cascade,

  role text,
  created_at timestamptz not null default now(),

  constraint performance_artists_unique_link unique (performance_id, artist_id)
);

create index if not exists performance_artists_performance_id_idx on public.performance_artists (performance_id);
create index if not exists performance_artists_artist_id_idx on public.performance_artists (artist_id);

alter table public.performance_artists enable row level security;

drop policy if exists "Public can read performance-artist links" on public.performance_artists;
create policy "Public can read performance-artist links"
  on public.performance_artists
  for select
  to anon, authenticated
  using (true);


-- ============================================================================
-- 9. public.company_manager_requests
-- ============================================================================

create table if not exists public.company_manager_requests (
  id uuid primary key default gen_random_uuid(),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  company_id uuid not null references public.companies (id) on delete cascade,
  user_id uuid not null references auth.users (id) on delete cascade,
  applicant_name text not null,
  applicant_email text not null,
  applicant_phone text,
  role_title text,
  proof_text text,
  status text not null default 'pending' check (status in ('pending', 'approved', 'rejected'))
);

create index if not exists company_manager_requests_company_idx on public.company_manager_requests (company_id);
create index if not exists company_manager_requests_user_idx on public.company_manager_requests (user_id);
create index if not exists company_manager_requests_status_idx on public.company_manager_requests (status);

drop trigger if exists trg_company_manager_requests_updated_at on public.company_manager_requests;
create trigger trg_company_manager_requests_updated_at
  before update on public.company_manager_requests
  for each row
  execute function public.set_updated_at();

alter table public.company_manager_requests enable row level security;

drop policy if exists "Users can view their own requests" on public.company_manager_requests;
create policy "Users can view their own requests"
  on public.company_manager_requests
  for select
  to authenticated
  using (user_id = auth.uid());

drop policy if exists "Users can insert claim requests" on public.company_manager_requests;
create policy "Users can insert claim requests"
  on public.company_manager_requests
  for insert
  to authenticated
  with check (user_id = auth.uid());
