"use client";
import { useMemo, useState } from "react";
import CompanyCard from "@/components/CompanyCard";
import { COMPANY_RECOMMENDATION_QUESTIONS, getFallbackCompanies, recommendCompanies } from "@/lib/companyRecommendation";
import type { Company } from "@/types";
import styles from "./CompanyRecommendationQuiz.module.css";
type QuizStage = "intro" | "questions" | "results";
export default function CompanyRecommendationQuiz({companies}:{companies:Company[]}){
 const[stage,setStage]=useState<QuizStage>("intro");const[selectedOptionIds,setSelectedOptionIds]=useState<string[]>([]);
 const recommendations=useMemo(()=>recommendCompanies(companies,selectedOptionIds,3),[companies,selectedOptionIds]);const fallbackCompanies=useMemo(()=>getFallbackCompanies(companies,3),[companies]);const isFallback=stage==="results"&&recommendations.length===0;
 const toggleOption=(id:string)=>setSelectedOptionIds(current=>current.includes(id)?current.filter(item=>item!==id):[...current,id]);const reset=()=>{setSelectedOptionIds([]);setStage("questions")};const close=()=>{setSelectedOptionIds([]);setStage("intro")};
 return <section className={styles.shell} aria-labelledby="company-recommendation-title"><div className={styles.header}><div><span className={`${styles.eyebrow} mono`}>POPOK MATCH</span><h2 id="company-recommendation-title" className={styles.title}>나와 잘맞는 단체 찾기</h2><p className={styles.description}>관심 분야와 작업 성향을 고르면 공개된 단체 정보에서 실제로 일치하는 항목을 찾아 추천해드려요. 로그인 없이 이용할 수 있으며 선택 내용은 저장되지 않습니다.</p></div>{stage==="intro"&&<button type="button" className={styles.primary} onClick={()=>setStage("questions")}>추천 시작하기</button>}</div>
 {stage==="questions"&&<><div className={styles.questions}>{COMPANY_RECOMMENDATION_QUESTIONS.map((question,index)=><div className={styles.question} key={question.id}><h3 className={styles.questionTitle}>Q{index+1}. {question.title} <span className={styles.hint}>(복수 선택)</span></h3><div className={styles.options}>{question.options.map(option=><button key={option.id} type="button" className={styles.option} aria-pressed={selectedOptionIds.includes(option.id)} onClick={()=>toggleOption(option.id)}>{option.label}</button>)}</div></div>)}</div><div className={styles.actions}><span className={styles.count}>{selectedOptionIds.length}개 항목 선택됨</span><button type="button" className={styles.primary} disabled={!selectedOptionIds.length} onClick={()=>setStage("results")}>나의 추천 결과 보기</button></div><div className={styles.closeRow}><button type="button" className={styles.closeButton} onClick={close}>추천 영역 닫기</button></div></>}
 {stage==="results"&&<><div className={styles.resultHeading}><h3>{isFallback?"POPOK 추천 단체":"나와 잘맞는 단체 TOP 3"}</h3><button type="button" className={styles.secondary} onClick={reset}>다시 선택하기</button></div>{isFallback&&<p className={styles.fallback}>선택 조건과 정확히 일치하는 정보가 부족해 POPOK 추천 단체를 함께 보여드립니다.</p>}<div className={styles.grid}>{(isFallback?fallbackCompanies:recommendations.map(r=>r.company)).map((company,index)=>{const recommendation=isFallback?null:recommendations[index];return <div className={styles.item} key={company.id}><div className={styles.meta}><div className={styles.topline}><span className={styles.rank}>추천 {index+1}위</span>{recommendation?<span className={styles.suitability}>적합도 {recommendation.percentage}%</span>:<span className={styles.pick}>POPOK 추천</span>}</div>{recommendation&&<><ul className={styles.reasons}>{recommendation.reasons.map(reason=><li key={reason}>{reason}</li>)}</ul><div className={styles.matchedItems} aria-label="실제로 일치한 항목">{recommendation.matchedItems.map(item=><span className={styles.matchedItem} key={item}>{item}</span>)}</div></>}</div><CompanyCard company={company}/></div>})}</div><div className={styles.closeRow}><button type="button" className={styles.closeButton} onClick={close}>추천 영역 닫기</button></div></>}
 </section>
}
