import test from "node:test";
import assert from "node:assert/strict";
import { balanceMagazinePerformances, filterPerformances, hasValidPoster, normalizePerformanceGenre, normalizePerformanceRegion, sortPerformances } from "../lib/performanceDiscovery.ts";

const performance = (overrides: Record<string, unknown> = {}) => ({ id:"1", title:"공연", genre:null, category:null, posterUrl:"https://example.com/poster.jpg", venue:"서울 예술극장", organizer:null, startDate:"2026-08-14", endDate:"2026-08-16", createdAt:"2026-08-01", featured:false, relatedArtists:[], ...overrides }) as any;

test("normalizes only explicit performance genre/category values",()=>{assert.equal(normalizePerformanceGenre(performance({genre:"현대무용"})),"dance");assert.equal(normalizePerformanceGenre(performance({genre:"국악",category:"traditional"})),"traditional");assert.equal(normalizePerformanceGenre(performance({genre:"클래식"})),"music");assert.equal(normalizePerformanceGenre(performance({category:"theater"})),"theater");assert.equal(normalizePerformanceGenre(performance({title:"피아노 리사이틀",genre:null,category:null})),"unclassified");});
test("poster policy rejects missing and common non-poster assets",()=>{assert.equal(hasValidPoster(performance({posterUrl:null})),false);assert.equal(hasValidPoster(performance({posterUrl:"https://example.com/assets/logo.png"})),false);assert.equal(hasValidPoster(performance()),true);});
test("normalizes region from verifiable venue and organizer text",()=>{assert.equal(normalizePerformanceRegion(performance()),"seoul");assert.equal(normalizePerformanceRegion(performance({venue:"부산문화회관"})),"gyeongsang");assert.equal(normalizePerformanceRegion(performance({venue:null,organizer:null})),"unknown");});
test("filters overlapping Seoul dance performances in Asia/Seoul date strings",()=>{const result=filterPerformances([performance({genre:"무용"}),performance({id:"2",genre:"국악"})],{genre:"dance",region:"seoul",q:"예술극장",quick:"week",today:"2026-08-12",weekEnd:"2026-08-16",monthEnd:"2026-08-31"});assert.equal(result.length,1);});
test("sorts stable and balances the all-genre magazine",()=>{const items=[performance({id:"d",genre:"무용"}),performance({id:"t",genre:"국악"}),performance({id:"d2",genre:"발레"})];assert.deepEqual(balanceMagazinePerformances(items).map((item:any)=>item.id),["d","t","d2"]);assert.equal(sortPerformances(items,"start-date","2026-08-12").length,3);});
