import test from "node:test"; import assert from "node:assert/strict"; import { readFileSync } from "node:fs"; import { fileURLToPath } from "node:url";
import { dedupeArtnuriByDocid, findDuplicate } from "../../lib/opportunities/dedupe.ts";
import { canonicalizeUrl, normalizeOrganization, normalizeTitle } from "../../lib/opportunities/normalize.ts";
import { getOpportunityLifecycleStatus, isOpportunityClosingSoon } from "../../lib/opportunities/status.ts";
import { planIngestion, selectRepresentativeOpportunities, validateOpportunity } from "../../lib/opportunities/ingestion.ts";
import { parseOpportunityDetail, parseOpportunityList } from "../../lib/opportunities/sources/parser.ts";
import { exceedsFailureThreshold } from "../../lib/opportunities/sources/fetch.ts";

test("normalizes titles, organizations, and tracking URLs", () => { assert.equal(normalizeTitle("[공고] 2026년  공연 모집!!"), "공연모집"); assert.equal(normalizeOrganization("(재) 예술 경영 지원센터"), "예술경영지원센터"); assert.equal(canonicalizeUrl("https://www.EXAMPLE.com/a/?utm_source=x&b=2"), "https://example.com/a?b=2"); });
test("computes lifecycle from the application window", () => { const now = new Date("2026-08-12T00:00:00+09:00"); assert.equal(getOpportunityLifecycleStatus(null,null,now),"undated"); assert.equal(getOpportunityLifecycleStatus("2026-08-20T00:00:00+09:00","2026-08-31T23:59:00+09:00",now),"upcoming"); assert.equal(getOpportunityLifecycleStatus("2026-08-01T00:00:00+09:00","2026-08-15T23:59:00+09:00",now),"open"); assert.equal(getOpportunityLifecycleStatus(null,"2026-08-01T23:59:00+09:00",now),"closed"); });
test("closing soon is derived without changing open lifecycle",()=>{const now=new Date("2026-08-12T00:00:00+09:00");assert.equal(getOpportunityLifecycleStatus("2026-08-01T00:00:00+09:00","2026-08-15T23:59:00+09:00",now),"open");assert.equal(isOpportunityClosingSoon("2026-08-15T23:59:00+09:00",now),true);});
test("preserves an explicit undated reason without inventing a deadline",()=>{const item={externalId:"S-undated",sourceUrl:"https://artnuri.or.kr/crawler/info/view.do?docid=S-undated",title:"상시 모집 공고",organization:"테스트재단"};const parsed=parseOpportunityDetail("artnuri",`<div class="info-tit"><strong class="ti">상시 모집 공고</strong></div><ul class="info-txt"><li><strong>온라인신청</strong><a class="site-link" href="https://publisher.example/apply">신청</a></li></ul><div class="supt-content">예산 소진 시까지 상시 모집</div>`,item);assert.equal(parsed.deadline,null);assert.equal(parsed.rawData?.deadlineEvidence,"상시 모집");assert.equal(validateOpportunity(parsed).valid,false);});
test("deduplicates Artnuri card/list variants by docid", () => { const items = parseOpportunityList("artnuri", `<a class="title" onclick="goView('S1','기관','001')">공고 A</a><a class="title" onclick="goView('S1','기관','001')">공고 A</a>`); assert.equal(items.length, 1); assert.equal(dedupeArtnuriByDocid(items).length, 1); });
test("parses source list fixtures", () => { const fixture=(name:string)=>readFileSync(fileURLToPath(new URL(`./fixtures/${name}`,import.meta.url)),"utf8"); assert.equal(parseOpportunityList("artnuri",fixture("artnuri-list.html")).length,1); assert.equal(parseOpportunityList("artmore",fixture("artmore-list.html")).length,1); assert.equal(parseOpportunityList("gokams_notice",fixture("kams-list.html")).length,1); });
test("parses the supplied Artnuri detail structure", () => { const fixture=(name:string)=>readFileSync(fileURLToPath(new URL(`./fixtures/${name}`,import.meta.url)),"utf8"); const [item]=parseOpportunityList("artnuri",fixture("artnuri-list.html")); const parsed=parseOpportunityDetail("artnuri",fixture("artnuri-detail.html"),item); assert.equal(parsed.externalId,"S100"); assert.equal(parsed.organization,"테스트문화재단"); assert.equal(parsed.region,"서울"); assert.equal(parsed.originalPublisherUrl,"https://publisher.example/apply"); assert.deepEqual(parsed.artGenres,["theatre_musical","dance"]); assert.equal(parsed.deadline,"2026-08-31T18:00:00+09:00"); });
test("marks cross-source duplicates as candidates, never deletion", () => { const common = { externalId: "1", canonicalSourceUrl: "https://a/1", normalizedOrganization: "기관", normalizedTitle: "공연예술지원", deadline: "2026-09-01" }; const match = findDuplicate({ ...common, source: "artnuri" }, [{ ...common, id: "old", source: "gokams_event", externalId: "2", canonicalSourceUrl: "https://b/2" }]); assert.equal(match?.kind, "cross_source_candidate"); });
test("requires title, organization, application window, and publisher URL before publication",()=>{const fixture=(name:string)=>readFileSync(fileURLToPath(new URL(`./fixtures/${name}`,import.meta.url)),"utf8");const [item]=parseOpportunityList("artnuri",fixture("artnuri-list.html"));const parsed=parseOpportunityDetail("artnuri",fixture("artnuri-detail.html"),item);assert.equal(validateOpportunity(parsed).valid,true);assert.deepEqual(validateOpportunity({...parsed,applicationStartAt:null,deadline:null,applicationUrl:null,originalPublisherUrl:null}).missing,["application_start_at","deadline","application_url"]);});
test("idempotent planner distinguishes new, changed, and unchanged",()=>{const fixture=(name:string)=>readFileSync(fileURLToPath(new URL(`./fixtures/${name}`,import.meta.url)),"utf8");const [item]=parseOpportunityList("artnuri",fixture("artnuri-list.html"));const parsed=parseOpportunityDetail("artnuri",fixture("artnuri-detail.html"),item);const first=planIngestion([parsed],[]);assert.equal(first.counts.new,1);const existing={...parsed,id:"id-1",createdAt:"2026-01-01",updatedAt:"2026-01-01"};assert.equal(planIngestion([parsed],[existing]).counts.unchanged,1);assert.deepEqual(planIngestion([{...parsed,summary:"변경"}],[existing]).plans[0].changedFields,["summary"]);});
test("stops a source only after minimum attempts exceed the failure threshold",()=>{assert.equal(exceedsFailureThreshold(1,2,0.3),false);assert.equal(exceedsFailureThreshold(1,3,0.3),true);assert.equal(exceedsFailureThreshold(1,4,0.3),false);});
