import { readFile } from "node:fs/promises"; import { createClient } from "@supabase/supabase-js";
import { crawlSource } from "../lib/opportunities/sources/fetch.ts"; import { planIngestion,validateForAutoPublish,type ExistingOpportunity } from "../lib/opportunities/ingestion.ts"; import { applyOpportunityPlan } from "../lib/opportunities/apply.ts";
const args=new Map(process.argv.slice(2).map((arg)=>{const [k,v="true"]=arg.replace(/^--/,"").split("=");return[k,v]}));const apply=args.has("apply");const source=args.get("source");const ref=args.get("confirm-project-ref");const maxNew=Number(args.get("max-new"));const maxPages=Number(args.get("max-pages"));
if(source!=="artnuri"||ref!=="sawsqtqjqmesfasbcmyf"||maxNew!==200||!Number.isInteger(maxPages)||maxPages<1||maxPages>20)throw new Error("Requires --source=artnuri --confirm-project-ref=sawsqtqjqmesfasbcmyf --max-new=200 --max-pages=1..20");if(apply&&args.get("confirm-publish")!=="validated-allowlist")throw new Error("Apply requires --confirm-publish=validated-allowlist");
const envFile=args.get("env-file");if(!envFile)throw new Error("--env-file is required");for(const line of(await readFile(envFile,"utf8")).split(/\r?\n/)){const m=line.match(/^([A-Z0-9_]+)=(.*)$/);if(m&&!process.env[m[1]])process.env[m[1]]=m[2].trim().replace(/^['\"]|['\"]$/g,"")}
const url=process.env.SUPABASE_URL||process.env.NEXT_PUBLIC_SUPABASE_URL;const key=process.env.SUPABASE_SERVICE_ROLE_KEY;if(!url||!key||new URL(url).hostname.split(".")[0]!==ref)throw new Error("Supabase project ref mismatch or missing server credentials");const client=createClient(url,key,{auth:{persistSession:false,autoRefreshToken:false}});
const {data:dbRows,error:dbError}=await client.from("opportunities").select("*");if(dbError)throw dbError;const existing:ExistingOpportunity[]=(dbRows??[]).map((r:any)=>({id:r.id,source:r.source,externalId:r.external_id,sourceUrl:r.source_url,canonicalSourceUrl:r.canonical_source_url,originalPublisherUrl:r.original_publisher_url,ingestionType:r.ingestion_type,title:r.title,normalizedTitle:r.normalized_title,organization:r.organization,normalizedOrganization:r.normalized_organization,opportunityType:r.opportunity_type,targetAudience:r.target_audience,artGenres:r.art_genres,region:r.region,summary:r.summary,description:r.description,applicationMethod:r.application_method,applicationUrl:r.application_url,contact:r.contact,thumbnailUrl:r.thumbnail_url,publishedAt:r.published_at,applicationStartAt:r.application_start_at,deadline:r.deadline,publicationStatus:r.publication_status,isFeatured:r.is_featured,isVerified:r.is_verified,createdAt:r.created_at,updatedAt:r.updated_at,lastScrapedAt:r.last_scraped_at,rawData:r.raw_data}));
const crawl=await crawlSource("artnuri",{maxPages,maxItems:200,timeoutMs:12000,delayMs:500,maxFailureRate:0.3});const plan=planIngestion(crawl.records,existing,crawl.discovered,crawl.failures.length);if(crawl.aborted||plan.counts.updated>0)throw new Error(`Unsafe plan: aborted=${crawl.aborted}, updated=${plan.counts.updated}`);const newPlans=plan.plans.filter((p)=>p.action==="new").slice(0,maxNew);if(newPlans.length>200)throw new Error("New record cap exceeded");
const reviews=newPlans.map((p)=>({externalId:p.record.externalId!,...validateForAutoPublish(p.record,crawl.records)}));const approved=reviews.filter((r)=>r.valid);const held=reviews.filter((r)=>!r.valid);const reasons:Record<string,number>={};for(const item of held)for(const reason of item.reasons)reasons[reason]=(reasons[reason]??0)+1;
for(const p of newPlans){const review=reviews.find((r)=>r.externalId===p.record.externalId)!;if(p.payload)p.payload.raw_data={...(p.payload.raw_data as object??{}),autoReview:{valid:review.valid,reasons:review.reasons,reviewedAt:new Date().toISOString()}};}
const report={projectRef:ref,mode:apply?"apply":"dry-run",pagesChecked:crawl.pagesChecked,counts:{...plan.counts,newSelected:newPlans.length,approved:approved.length,held:held.length},holdReasons:reasons,approvedExternalIds:approved.map((r)=>r.externalId),heldRecords:held,skippedRecords:plan.plans.filter((p)=>p.action==="skipped").map((p)=>({externalId:p.record.externalId,reason:p.reason})),failures:crawl.failures};console.log(JSON.stringify(report,null,2));
if(!apply)process.exit(0);if(newPlans.length===0||approved.length===0||approved.length===newPlans.length)throw new Error(`Anomalous approval distribution; refusing apply (${approved.length}/${newPlans.length})`);
const inserted=await applyOpportunityPlan(client,newPlans,true);for(let i=0;i<approved.length;i+=50){const ids=approved.slice(i,i+50).map((r)=>r.externalId);const {error}=await client.from("opportunities").update({publication_status:"published",review_status:"approved",is_verified:true}).eq("source","artnuri").in("external_id",ids);if(error)throw error;}
const now=new Date().toISOString();const {error:runError}=await client.from("opportunity_ingestion_runs").insert({source:"artnuri",mode:"apply",status:"completed",pages_checked:crawl.pagesChecked,items_found:crawl.discovered,items_parsed:crawl.records.length,items_failed:crawl.failures.length,summary:{...plan.counts,inserted:inserted.applied,approved:approved.length,held:held.length,approvedExternalIds:approved.map((r)=>r.externalId),heldExternalIds:held.map((r)=>r.externalId),holdReasons:reasons},started_at:now,finished_at:now});if(runError)throw runError;console.log(JSON.stringify({applied:true,inserted:inserted.applied,published:approved.length,held:held.length}));
